### PR TITLE
Copy node's Buffer class

### PR DESCRIPTION
**Pull request by wadey**
Thanks for node-mmap! I wanted to have more of the functionality of node's Buffer class, so I copied it here and made it use mmap for the memory instead of allocating space. I was hoping that I could do this using a subclass, but the Buffer class has a private constructor.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Wadey, I don't like that it duplicates gobs of code from the nodejs core, that's bound to become a maintenance hassle.

The C++ Buffer API in node 0.3.x allows you to use an arbitrary chunk of memory as a buffer, why don't you use that? I can give you some pointers if you want.

**Comment by wadey** [comment]
That makes sense. I haven't moved to using Node 0.3.x yet as it is still considered unstable. I'll probably hold off and wait for that. I'm going to close this pull request and move it to a different branch on my fork.

I still think you should merge in the package.json file and submit this to npm though :)

**Comment by bnoordhuis** [comment]
I will, thanks for that. :)

PS: As a quickie example of what the 0.3.x buffer interface looks like:

https://github.com/bnoordhuis/node-mmap/blob/buffers/mmap.cc#L41

**Comment by wadey** [comment]
Wow, that is really nice. I'm glad they made the 0.3 API so much simpler :)

**Comment by bpedro** [comment]
Great stuff, I've been wanting that for some time now. Thanks!

**Comment by bnoordhuis** [comment]
I take it this is something people would like to see, even if it's 0.3.x only?

I've put off publishing node-mmap to npm because I couldn't decide if it should be backwards compatible with 0.2.x or not. Input would be much appreciated.

**Comment by wadey** [comment]
Now that 0.4.0 stable has been released I vote that you release the newer version to npm.

**Comment by bnoordhuis** [comment]
Vote registered, motion passed. I've published two versions, one for 0.2.x and one for 0.4.x.

http://search.npmjs.org/#/mmap

**Pull request closed without merging**
